### ISSUE TITLE
Wont work: freezes when opening an emulator, won't flash either.

### ISSUE THREAD

**Issue by lolmaus** [jfm92/microByte#8]
Hi! Got MicroByte from CrowdSupply but cannot make it run.

I've formatted a 32 GB MicroSD card to FAT32 with default allocation size.

I've inserted the card into MicroByte to generate folders, then copied 128 uncompressed GameBoy games (`.gb` file extension) and 91 uncompressed GameBoy Color games (`.gbc` file extension) to the corresponding folders.

The device freezes when I select GameBoy or GameBoy Color in the Emulators section. 

If I select any other emulator, it displays "Oops! Any game available." and then freezes in a weird way: I see the Emulators menu item, I cannot go left, right or up. When I hit A, I see the settings menu. When I go up (B), I see the Emulators menu item again.

The device reports firmware version `v0.6-41-g4064fdc-dirty`.

I put the [microByte_0.83.bin](https://github.com/jfm92/microByte_firmware/releases/tag/v0.83) file into the MicroSD root. This let me enter the `Update firmware` submenu. But the only item there is mangled. It's eiether just `?` or something weird like `?6@@bla` (cannot remember exactly`. When I select this item, the device reboots immediately and reports the old version.

Please help.

**Comment by coleprime** [comment]
Exact same problems with mine.  :/

However, I was able to force the upgrade by putting v0.2 in apps folder, run it from there to downgrade, then run v0.83 from apps folder also and upgrade worked.

**Comment by MarcusE1W** [comment]
Late to the party, but I can confirm this works.

**Comment by lolmaus** [comment]
@MarcusE1W What works?
